"""Catalog entries for the later trend-category indicator kinds, in catalog order."""

from __future__ import annotations

from thytrader.strategies.indicator_spec_model import (
    _CLOSE,
    _TREND,
    IndicatorKindSpec,
    IndicatorParameterSpec,
    _configurable,
    _integer,
    _locked,
    _multiplier,
    _period,
)
from thytrader.strategies.models import (
    CLOSE_VOLUME_INPUT,
    HL_INPUT,
    HLC_INPUT,
    IndicatorKind,
)

_TREND_SPECS: tuple[IndicatorKindSpec, ...] = (
    _configurable(
        IndicatorKind.DEMA,
        "DEMA",
        _TREND,
        "Double EMA, 2 * EMA - EMA(EMA): less lag than a plain EMA.",
        parameters=(_period(20, help_text="Window of both chained EMAs."),),
        warmup="2 * period - 1",
    ),
    _configurable(
        IndicatorKind.TEMA,
        "TEMA",
        _TREND,
        "Triple EMA, 3 * EMA - 3 * EMA(EMA) + EMA(EMA(EMA)).",
        parameters=(_period(20, help_text="Window of all three chained EMAs."),),
        warmup="3 * period - 2",
    ),
    _configurable(
        IndicatorKind.HMA,
        "Hull MA",
        _TREND,
        "Hull moving average: WMA(2 * WMA(n/2) - WMA(n), √n), with n/2 and √n floored.",
        parameters=(_period(20, help_text="Hull length n."),),
        warmup="period + floor(sqrt(period)) - 1",
    ),
    _configurable(
        IndicatorKind.KAMA,
        "KAMA",
        _TREND,
        "Kaufman adaptive MA: moves fast in efficient trends, slowly in noise.",
        parameters=(
            _period(10, maximum=100, help_text="Efficiency-ratio lookback in price changes."),
            _integer(
                "fast_period",
                "Fast period",
                default=2,
                maximum=100,
                help_text="EMA-equivalent period of the fastest smoothing.",
            ),
            _integer(
                "slow_period",
                "Slow period",
                default=30,
                minimum=3,
                help_text="EMA-equivalent period of the slowest smoothing.",
            ),
        ),
        warmup="period + 1",
        parameter_kind="kama",
        constraints=("fast_period < slow_period",),
    ),
    _locked(
        IndicatorKind.VWMA,
        "VWMA",
        _TREND,
        "Volume-weighted moving average of close.",
        inputs=CLOSE_VOLUME_INPUT,
        parameters=(_period(20),),
        warmup="period",
    ),
    _locked(
        IndicatorKind.SUPERTREND,
        "Supertrend",
        _TREND,
        "ATR band that trails the trend; direction is 1 (up) or -1 (down).",
        inputs=HLC_INPUT,
        parameters=(
            _period(10, maximum=100, label="ATR period", help_text="Wilder ATR period."),
            _multiplier("multiplier", "Multiplier", "3", "ATR multiple for the bands."),
        ),
        warmup="period",
        parameter_kind="supertrend",
    ),
    _locked(
        IndicatorKind.PARABOLIC_SAR,
        "Parabolic SAR",
        _TREND,
        "Wilder stop-and-reverse that accelerates toward the trend's extreme point.",
        inputs=HL_INPUT,
        parameters=(
            IndicatorParameterSpec(
                name="step",
                label="Step",
                value_type="decimal",
                minimum="0",
                maximum="1",
                default="0.02",
                help="Acceleration start and increment per new extreme.",
                exclusive_minimum=True,
            ),
            IndicatorParameterSpec(
                name="max_step",
                label="Max step",
                value_type="decimal",
                minimum="0",
                maximum="1",
                default="0.2",
                help="Acceleration cap (at least step).",
                exclusive_minimum=True,
            ),
        ),
        warmup="2",
        parameter_kind="parabolic_sar",
        constraints=("step <= max_step",),
    ),
    _locked(
        IndicatorKind.AROON,
        "Aroon",
        _TREND,
        "Bars since the period high and low, scaled 0 to 100, and their difference.",
        inputs=HL_INPUT,
        parameters=(_period(25, help_text="Lookback; the window holds period + 1 bars."),),
        warmup="period + 1",
    ),
    _locked(
        IndicatorKind.ICHIMOKU,
        "Ichimoku",
        _TREND,
        "Conversion, base, and leading-span midpoints on the current bar (no displacement).",
        inputs=HL_INPUT,
        parameters=(
            _integer(
                "tenkan_period",
                "Tenkan period",
                default=9,
                maximum=498,
                help_text="Conversion line.",
            ),
            _integer(
                "kijun_period",
                "Kijun period",
                default=26,
                minimum=3,
                maximum=499,
                help_text="Base line.",
            ),
            _integer(
                "senkou_b_period",
                "Senkou B period",
                default=52,
                minimum=4,
                help_text="Leading span B midpoint window.",
            ),
        ),
        warmup="max(tenkan_period, kijun_period, senkou_b_period)",
        parameter_kind="ichimoku",
        constraints=("tenkan_period < kijun_period < senkou_b_period",),
    ),
    _locked(
        IndicatorKind.VORTEX,
        "Vortex",
        _TREND,
        "Upward (VI+) and downward (VI-) vortex movement over true range.",
        inputs=HLC_INPUT,
        parameters=(_period(14, help_text="Previous-bar comparisons in each sum."),),
        warmup="period + 1",
    ),
    _configurable(
        IndicatorKind.LINEAR_REGRESSION,
        "Linear regression",
        _TREND,
        "Least-squares line over period bars: endpoint value and slope per bar.",
        parameters=(_period(20),),
        warmup="period",
    ),
    _locked(
        IndicatorKind.TRIX,
        "TRIX",
        _TREND,
        "Percent change of a triple-smoothed EMA of close.",
        inputs=_CLOSE,
        parameters=(_period(15, help_text="Window of each of the three EMAs."),),
        warmup="3 * period - 1",
    ),
)
