"""Catalog entries for the historical 21 indicator kinds, in catalog order.

They come first in ``INDICATOR_KIND_SPECS``; later kinds live in the per-category modules.
"""

from __future__ import annotations

from thytrader.strategies.indicator_spec_model import (
    _BOLLINGER_PARAMETERS,
    _CLOSE,
    _FAST_SLOW_SIGNAL,
    _MOMENTUM,
    _PRICE,
    _TREND,
    _VOLATILITY,
    _VOLUME,
    OHLCV_FIELDS,
    IndicatorKindSpec,
    IndicatorParameterSpec,
    _configurable,
    _integer,
    _locked,
    _period,
)
from thytrader.strategies.models import (
    HLC_INPUT,
    HLCV_INPUT,
    IndicatorKind,
)

_EXISTING_SPECS: tuple[IndicatorKindSpec, ...] = (
    _configurable(
        IndicatorKind.EMA,
        "EMA",
        _TREND,
        "Exponential moving average, seeded by the SMA of the first period values.",
        parameters=(_period(20, help_text="EMA window; smoothing is 2 / (period + 1)."),),
        warmup="period",
    ),
    _configurable(
        IndicatorKind.SMA,
        "SMA",
        _TREND,
        "Arithmetic mean of the last period values.",
        parameters=(_period(20),),
        warmup="period",
    ),
    _locked(
        IndicatorKind.RSI,
        "RSI",
        _MOMENTUM,
        "Wilder relative strength index (0 to 100) over period closing changes.",
        inputs=_CLOSE,
        parameters=(_period(14, maximum=100, help_text="Closing changes in the Wilder average."),),
        warmup="period + 1",
    ),
    _locked(
        IndicatorKind.ATR,
        "ATR",
        _VOLATILITY,
        "Wilder average true range. Initial and trailing stops reference an ATR.",
        inputs=HLC_INPUT,
        parameters=(_period(14, maximum=100, help_text="True ranges in the Wilder average."),),
        warmup="period",
    ),
    _locked(
        IndicatorKind.VOLUME_SMA,
        "Volume SMA",
        _VOLUME,
        "Arithmetic mean of volume over period bars.",
        inputs=("volume",),
        parameters=(_period(20),),
        warmup="period",
    ),
    _configurable(
        IndicatorKind.HIGHEST,
        "Highest",
        _PRICE,
        "Highest value of the source over period bars, current bar included.",
        parameters=(_period(20),),
        warmup="period",
        default_input="high",
    ),
    _configurable(
        IndicatorKind.LOWEST,
        "Lowest",
        _PRICE,
        "Lowest value of the source over period bars, current bar included.",
        parameters=(_period(20),),
        warmup="period",
        default_input="low",
    ),
    _configurable(
        IndicatorKind.STDEV,
        "Stdev",
        _VOLATILITY,
        "Population standard deviation of the source over period bars.",
        parameters=(_period(20),),
        warmup="period",
    ),
    _configurable(
        IndicatorKind.STDEV_SAMPLE,
        "Sample stdev",
        _VOLATILITY,
        "Sample (N - 1) standard deviation of the source over period bars.",
        parameters=(_period(20),),
        warmup="period",
    ),
    _configurable(
        IndicatorKind.ROC,
        "ROC",
        _MOMENTUM,
        "Percent change versus the value exactly period bars ago.",
        parameters=(_period(10, help_text="Lookback in bars."),),
        warmup="period + 1",
    ),
    _locked(
        IndicatorKind.WILLIAMS_R,
        "Williams %R",
        _MOMENTUM,
        "Close within the period high-low range: -100 at the low, 0 at the high.",
        inputs=HLC_INPUT,
        parameters=(_period(14, maximum=100),),
        warmup="period",
    ),
    _locked(
        IndicatorKind.CCI,
        "CCI",
        _MOMENTUM,
        "Commodity channel index of typical price (Lambert constant 0.015).",
        inputs=HLC_INPUT,
        parameters=(_period(20, maximum=100),),
        warmup="period",
    ),
    _configurable(
        IndicatorKind.WMA,
        "WMA",
        _TREND,
        "Linearly weighted moving average; the newest bar weighs period.",
        parameters=(_period(20),),
        warmup="period",
    ),
    _configurable(
        IndicatorKind.MOMENTUM,
        "Momentum",
        _MOMENTUM,
        "Source minus the source exactly period bars ago.",
        parameters=(_period(10, help_text="Lookback in bars."),),
        warmup="period + 1",
    ),
    _locked(
        IndicatorKind.MFI,
        "MFI",
        _VOLUME,
        "Money flow index (0 to 100): volume-weighted RSI of typical price.",
        inputs=HLCV_INPUT,
        parameters=(_period(14, maximum=100, help_text="Typical-price changes in the window."),),
        warmup="period + 1",
    ),
    _locked(
        IndicatorKind.MACD,
        "MACD",
        _MOMENTUM,
        "EMA(fast) - EMA(slow) with an EMA signal line and histogram.",
        inputs=_CLOSE,
        parameters=_FAST_SLOW_SIGNAL,
        warmup="slow_period + signal_period - 1",
        parameter_kind="macd",
        constraints=("fast_period < slow_period",),
    ),
    _locked(
        IndicatorKind.BOLLINGER,
        "Bollinger",
        _VOLATILITY,
        "SMA middle band with bands a multiple of population stdev away.",
        inputs=_CLOSE,
        parameters=_BOLLINGER_PARAMETERS,
        warmup="period",
        parameter_kind="bollinger",
    ),
    _locked(
        IndicatorKind.STOCHASTIC,
        "Stochastic",
        _MOMENTUM,
        "Fast stochastic: %K is close within the high-low range, %D its SMA.",
        inputs=HLC_INPUT,
        parameters=(
            _integer(
                "k_period", "%K period", default=14, maximum=100, help_text="High-low window."
            ),
            _integer("d_period", "%D period", default=3, help_text="SMA of %K."),
        ),
        warmup="k_period + d_period - 1",
        parameter_kind="stochastic",
    ),
    _locked(
        IndicatorKind.ADX,
        "ADX",
        _TREND,
        "Wilder ADX trend strength with +DI and -DI.",
        inputs=HLC_INPUT,
        parameters=(_period(14, maximum=100, help_text="Wilder smoothing period."),),
        warmup="2 * period - 1",
    ),
    IndicatorKindSpec(
        kind=IndicatorKind.IDENTITY,
        label="OHLCV",
        category=_PRICE,
        summary="Copies one candle field (open, high, low, close, or volume).",
        input_mode="configurable",
        inputs=OHLCV_FIELDS,
        default_input="close",
        parameter_kind="none",
        parameters=(),
        warmup="1",
    ),
    IndicatorKindSpec(
        kind=IndicatorKind.CONSTANT,
        label="Constant",
        category=_PRICE,
        summary="A fixed level on every bar, for example an RSI threshold to cross.",
        input_mode="none",
        inputs=(),
        default_input=None,
        parameter_kind="value",
        parameters=(
            IndicatorParameterSpec(
                name="value",
                label="Value",
                value_type="decimal",
                minimum=None,
                maximum=None,
                default="50",
                help="Exact decimal level, for example 30 or -0.5.",
            ),
        ),
        warmup="1",
    ),
)
