"""Catalog entries for the later momentum-category indicator kinds, in catalog order."""

from __future__ import annotations

from thytrader.strategies.indicator_spec_model import (
    _CLOSE,
    _FAST_SLOW_SIGNAL,
    _MOMENTUM,
    IndicatorKindSpec,
    _integer,
    _locked,
    _period,
)
from thytrader.strategies.models import (
    HL_INPUT,
    HLC_INPUT,
    IndicatorKind,
)

_MOMENTUM_SPECS: tuple[IndicatorKindSpec, ...] = (
    _locked(
        IndicatorKind.STOCHASTIC_RSI,
        "Stochastic RSI",
        _MOMENTUM,
        "Stochastic of RSI (0 to 100) with SMA-smoothed %K and %D.",
        inputs=_CLOSE,
        parameters=(
            _integer("rsi_period", "RSI period", default=14, maximum=100, help_text="Wilder RSI."),
            _integer(
                "stoch_period",
                "Stochastic period",
                default=14,
                maximum=100,
                help_text="RSI high-low window.",
            ),
            _integer(
                "k_period",
                "%K smoothing",
                default=3,
                minimum=1,
                maximum=100,
                help_text="SMA of the raw stochastic RSI (1 = none).",
            ),
            _integer(
                "d_period",
                "%D smoothing",
                default=3,
                minimum=1,
                maximum=100,
                help_text="SMA of %K.",
            ),
        ),
        warmup="rsi_period + stoch_period + k_period + d_period - 2",
        parameter_kind="stochastic_rsi",
    ),
    _locked(
        IndicatorKind.PPO,
        "PPO",
        _MOMENTUM,
        "Percentage price oscillator: 100 * (EMA fast - EMA slow) / EMA slow, with signal.",
        inputs=_CLOSE,
        parameters=_FAST_SLOW_SIGNAL,
        warmup="slow_period + signal_period - 1",
        parameter_kind="macd",
        constraints=("fast_period < slow_period",),
    ),
    _locked(
        IndicatorKind.ULTIMATE_OSCILLATOR,
        "Ultimate Oscillator",
        _MOMENTUM,
        "Buying pressure over true range in three windows, weighted 4:2:1 (0 to 100).",
        inputs=HLC_INPUT,
        parameters=(
            _integer(
                "short_period",
                "Short period",
                default=7,
                maximum=98,
                help_text="Shortest window, weight 4.",
            ),
            _integer(
                "medium_period",
                "Medium period",
                default=14,
                minimum=3,
                maximum=99,
                help_text="Middle window, weight 2.",
            ),
            _integer(
                "long_period",
                "Long period",
                default=28,
                minimum=4,
                maximum=100,
                help_text="Longest window, weight 1.",
            ),
        ),
        warmup="long_period + 1",
        parameter_kind="ultimate_oscillator",
        constraints=("short_period < medium_period < long_period",),
    ),
    _locked(
        IndicatorKind.AWESOME_OSCILLATOR,
        "Awesome Oscillator",
        _MOMENTUM,
        "SMA(fast) - SMA(slow) of the median price (high + low) / 2.",
        inputs=HL_INPUT,
        parameters=(
            _integer(
                "fast_period",
                "Fast period",
                default=5,
                maximum=499,
                help_text="Fast median SMA.",
            ),
            _integer(
                "slow_period",
                "Slow period",
                default=34,
                minimum=3,
                help_text="Slow median SMA.",
            ),
        ),
        warmup="slow_period",
        parameter_kind="awesome_oscillator",
        constraints=("fast_period < slow_period",),
    ),
    _locked(
        IndicatorKind.CMO,
        "CMO",
        _MOMENTUM,
        "Chande momentum oscillator (-100 to 100) from summed gains and losses.",
        inputs=_CLOSE,
        parameters=(_period(9, maximum=100, help_text="Closing changes in the sums."),),
        warmup="period + 1",
    ),
    _locked(
        IndicatorKind.TSI,
        "TSI",
        _MOMENTUM,
        "True strength index: double-smoothed momentum over its absolute value, with signal.",
        inputs=_CLOSE,
        parameters=(
            _integer(
                "long_period",
                "Long period",
                default=25,
                minimum=3,
                help_text="First EMA smoothing.",
            ),
            _integer(
                "short_period",
                "Short period",
                default=13,
                maximum=499,
                help_text="Second EMA smoothing.",
            ),
            _integer("signal_period", "Signal period", default=13, help_text="EMA of TSI."),
        ),
        warmup="long_period + short_period + signal_period - 1",
        parameter_kind="tsi",
        constraints=("short_period < long_period",),
    ),
)
