"""Operator lane chat tools: read-only diagnostics over the operator HTTP reports.

None of these tools mutates state or trades. `tools._TOOLS` lists this lane first.
"""

from __future__ import annotations

from thytrader.operator_chat.models import ChatLane
from thytrader.operator_chat.tool_spec import (
    _PRODUCT,
    _TIMEFRAME,
    ChatTool,
    _opt_string,
)

OPERATOR_TOOLS: tuple[ChatTool, ...] = (
    ChatTool(
        name="operator_health",
        description="Read-only health. Never trades.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/health",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="operator_configuration",
        description="Redacted configuration. Omits secrets. Coinbase flags are booleans only.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/configuration",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="operator_exchange",
        description="Coinbase connectivity and detected permissions. No balances or keys.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/exchange",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="operator_market_data",
        description="Freshness and gaps for one product and timeframe. Never interpolate.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/market-data",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={"product_id": _PRODUCT, "timeframe": _TIMEFRAME},
        required=(),
    ),
    ChatTool(
        name="operator_data_catalog",
        description="Local datasets, watchlist, and watch_complete coverage.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/data-catalog",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="operator_products",
        description="Enabled USD spot products.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/products",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="operator_indicators",
        description="Implemented indicator catalog.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/indicators",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="operator_strategies",
        description="Draft, publication, and runtime status without order payloads.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/strategies",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="operator_runtime",
        description="Paper/live status without trading.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/runtime",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={"deployment_id": _opt_string("Optional deployment UUID.")},
        required=(),
    ),
    ChatTool(
        name="operator_monitor",
        description="Deployments, recent journals, and notify delivery.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/monitor",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="operator_performance",
        description="Backtest or runtime performance slice.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/performance",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={
            "result_fingerprint": _opt_string("sha256: plus 64 hex."),
            "deployment_id": _opt_string("Deployment UUID."),
        },
        required=(),
    ),
    ChatTool(
        name="operator_risk",
        description="Risk-policy registry identity and pause/mismatch findings. No balances.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/risk",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="operator_reconciliation",
        description="Unknown-order and mismatch findings.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/reconciliation",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="operator_support_bundle",
        description="Redacted diagnostic bundle. Secrets stay omitted.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/support-bundle",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="operator_studies",
        description="Persisted research study catalog without trading authority.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/studies",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="operator_trade_reasons",
        description="Why-trade journals and review notes without order payloads.",
        lane=ChatLane.OPERATOR,
        method="GET",
        path="/api/v1/operator/trade-reasons",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
)
