"""Memory lane chat tools: journals, sentiment, patterns, notify, and memory models.

`tools._TOOLS` lists this lane last.
"""

from __future__ import annotations

from thytrader.operator_chat.models import ChatLane
from thytrader.operator_chat.tool_spec import (
    _UUID,
    ChatTool,
    _integer,
    _opt_string,
    _string,
)

MEMORY_TOOLS: tuple[ChatTool, ...] = (
    ChatTool(
        name="memory_status",
        description="Journal/hook counts and redacted notify configuration.",
        lane=ChatLane.MEMORY,
        method="GET",
        path="/api/v1/memory",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="memory_monitor",
        description="Memory monitor snapshot.",
        lane=ChatLane.MEMORY,
        method="GET",
        path="/api/v1/memory/monitor",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="memory_list_journals",
        description="List newest-first journals.",
        lane=ChatLane.MEMORY,
        method="GET",
        path="/api/v1/memory/journals",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={
            "origin": _opt_string("human or agent."),
            "kind": _opt_string("fact, lesson, or note."),
        },
        required=(),
    ),
    ChatTool(
        name="memory_add_journal",
        description="Append an origin-attributed journal. YOLO never covers memory.",
        lane=ChatLane.MEMORY,
        method="POST",
        path="/api/v1/memory/journals",
        mutation=True,
        yolo="none",
        hard_gate=True,
        live_ack="never",
        properties={
            "origin": _string("human or agent."),
            "kind": _string("fact, lesson, or note."),
            "title": _string("Title."),
            "body": _string("Body."),
            "product_id": _opt_string("Optional product."),
            "runtime_mode": _opt_string("none, backtest, paper, or live."),
            "lesson_outcome": _opt_string("Required for lessons."),
        },
        required=("origin", "kind", "title", "body"),
    ),
    ChatTool(
        name="memory_add_sentiment",
        description="Append a sentiment snapshot. YOLO never covers memory.",
        lane=ChatLane.MEMORY,
        method="POST",
        path="/api/v1/memory/sentiment",
        mutation=True,
        yolo="none",
        hard_gate=True,
        live_ack="never",
        properties={
            "origin": _string("human or agent."),
            "label": _string("bullish, bearish, neutral, or unknown."),
            "product_id": _opt_string("Optional product."),
            "note": _opt_string("Optional note."),
        },
        required=("origin", "label"),
    ),
    ChatTool(
        name="memory_add_pattern",
        description="Append a pattern-learning hook. YOLO never covers memory.",
        lane=ChatLane.MEMORY,
        method="POST",
        path="/api/v1/memory/patterns",
        mutation=True,
        yolo="none",
        hard_gate=True,
        live_ack="never",
        properties={
            "origin": _string("human or agent."),
            "pattern_key": _string("Stable pattern key."),
            "name": _string("Display name."),
            "hypothesis": _string("Hypothesis."),
            "status": _string("hypothesized, supported, contradicted, or retired."),
        },
        required=("origin", "pattern_key", "name", "hypothesis", "status"),
    ),
    ChatTool(
        name="memory_notify",
        description="Request a user notification. YOLO never covers memory.",
        lane=ChatLane.MEMORY,
        method="POST",
        path="/api/v1/memory/notifications",
        mutation=True,
        yolo="none",
        hard_gate=True,
        live_ack="never",
        properties={
            "origin": _string("human or agent."),
            "title": _string("Title."),
            "body": _string("Body."),
            "severity": _opt_string("info, warning, or critical."),
        },
        required=("origin", "title", "body"),
    ),
    ChatTool(
        name="memory_list_models",
        description=(
            "List trained experiential models. Advisory research input only, not a live brain."
        ),
        lane=ChatLane.MEMORY,
        method="GET",
        path="/api/v1/memory/models",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={},
        required=(),
    ),
    ChatTool(
        name="memory_show_model",
        description="Show one trained experiential model. Advisory only.",
        lane=ChatLane.MEMORY,
        method="GET",
        path="/api/v1/memory/models/{model_id}",
        mutation=False,
        yolo="none",
        hard_gate=False,
        live_ack="never",
        properties={"model_id": _UUID},
        required=("model_id",),
    ),
    ChatTool(
        name="memory_train",
        description=(
            "Train thytrader-experiential-train-v1 from attributed local journals. "
            "Confirmation-hard-gated. Advisory research input only; never a live brain."
        ),
        lane=ChatLane.MEMORY,
        method="POST",
        path="/api/v1/memory/models",
        mutation=True,
        yolo="none",
        hard_gate=True,
        live_ack="never",
        properties={
            "origin": _string("human or agent."),
            "seed": _integer("Optional RNG seed. Default 1."),
        },
        required=("origin",),
    ),
)
